login: ""  # Ваш логин он ВКонтакте
password: ""  # Ваш пароль он ВКонтакте
# token: "vk1.a.TP7zfg_MalF7us0s_FZzEEYUnK1PaRgkdwcBB1_a7mma8g288qBvNz94jZYjluScSEIewhURwE7rnfq4P6Ht0IwNyGjUFlOGxoMSoEynSnbLBFwiYbzCPPRc95VPOJUlUiey_qLITmYCqvud-hFPKC4mkyets3XzNAmpvC7EUElfYJ2HJ2By3mSG1-bxzWEZ5qFhfDkKCHXCnQu4ZiSYgg"  # Ваш токен (для скачивания фото участников беседы)
token: "vk1.a.nF7Rm0Dnv4ua9zvqBrt5ywiD9jzCoyPyIipD7WvZcQkVYNGgbjdDKekxvaecglgQ3ptZTYMNiOmau6CLKaHAKDpE-VmvdDJ2yv2JcZYik0gFh9wutT686W5y1x1KYM-0TVqrV9eoMamLWyOAVtJWejqWgJ-CUdZEPULOtRColyYFVs2Cdv3xuU-MTeolWL_ZVzxZPTTkW8iL_yCdbH9Iyg"
# token: ""
